name: update flake inputs

on:
  schedule:
    # every Monday at 04:00 UTC
    - cron: "0 4 * * 1"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: DeterminateSystems/update-flake-lock@834c491b2ece4de0bbd00d85214bb5e83b4da5c6 # v28
        with:
          commit-msg: "chore(deps): update flake.lock"
          pr-title: "chore(deps): update flake.lock"
          pr-labels: |
            dependencies
            automated